### ISSUE TITLE
Fails to build without libnetcdf dependency

### ISSUE THREAD

**Issue by julian1** [aodn/geoserver-build#110]
```
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /tmp/jna6629583319403885393.tmp which might have disabled stack guard. The VM will try to fix the stack guard now.
SUREFIRE-859: It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.148 sec <<< FAILURE! - in au.org.emii.gogoduck.worker.GoGoDuckModuleTest
testUpdateMetadata(au.org.emii.gogoduck.worker.GoGoDuckModuleTest)  Time elapsed: 0.146 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: Unable to load library 'netcdf': libnetcdf.so: cannot open shared object file: No such file or directory
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:145)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:188)
        at com.sun.jna.Library$Handler.<init>(Library.java:123)
        at com.sun.jna.Native.loadLibrary(Native.java:255)
        at com.sun.jna.Native.loadLibrary(Native.java:241)
        at ucar.nc2.jni.netcdf.Nc4Iosp.load(Nc4Iosp.java:155)
        at ucar.nc2.jni.netcdf.Nc4Iosp._open(Nc4Iosp.java:234)
        at ucar.nc2.jni.netcdf.Nc4Iosp.openForWriting(Nc4Iosp.java:230)
        at ucar.nc2.NetcdfFileWriter.<init>(NetcdfFileWriter.java:196)
        at ucar.nc2.NetcdfFileWriter.openExisting(NetcdfFileWriter.java:105)
        at au.org.emii.gogoduck.worker.GoGoDuckModule.updateMetadata(GoGoDuckModule.java:153)
        at au.org.emii.gogoduck.worker.GoGoDuckModuleTest.testUpdateMetadata(GoGoDuckModuleTest.java:61)
```

Solution is sudo apt-get install libnetcdf-dev, which should probably be documented

**Comment by jonescc** [comment]
libnetcdf-dev doesn't look to be required for javaduck at least.  libnetcdf works fine for me.  Will update javaducks doco - its not worth updating the nco tools version.
