### ISSUE TITLE
Variable filler, min, max and valid range types should default to variable type if not specified

### ISSUE THREAD

**Issue by jonescc** [aodn/geoserver-build#229]
### To Reproduce

Specify an aggregation override like the following in an aggregation template:

```
        <variable name="sea_surface_temperature" type="Float">
            <attribute name="_FillValue" value="9.9692099683868690e+36"/>
            <attribute name="valid_min" value="0.0"/>
            <attribute name="valid_max" value="350.0"/>
        </variable>
```

### What happens

```
java.lang.NullPointerException
	at au.org.emii.aggregator.datatype.NumericTypes.get(NumericTypes.java:10)
	at au.org.emii.aggregator.datatype.NumericTypes.parse(NumericTypes.java:51)
	at au.org.emii.aggregator.overrides.VariableAttributeOverride.getAttributeNumericValue(VariableAttributeOverride.java:46)
	at au.org.emii.aggregator.overrides.VariableOverrides.getAttributeNumericValue(VariableOverrides.java:88)
	at au.org.emii.aggregator.overrides.VariableOverrides.getFillerValue(VariableOverrides.java:45)
	at au.org.emii.aggregator.NetcdfAggregator.getUnpackerOverrides(NetcdfAggregator.java:249)
```
### What I expect to happen

The type of the fill_value, valid_min, valid_max is set to the variable type

**Comment by jonescc** [comment]
Fixed by  https://github.com/aodn/geoserver-build/commit/fe0b35bc01a7e6ff8aa016e8f6d854dae4d71b76
