### ISSUE TITLE
Error when trying to get netcdf

### ISSUE THREAD

**Issue by jkburges** [aodn/geoserver-build#49]
An exception occurs when trying to generate a NetCDF under certain conditions.

**Steps to reproduce**
From the command line:

1. cd src/extension/ncdfgenerator
1. mvn exec:java -Dexec.mainClass=au.org.emii.ncdfgenerator.Main -Dexec.args="-d jdbc:postgresql://dbprod.emii.org.au:5432/harvest?loginTimeout=1000&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory -u HERE_BE_USER -p HERE_BE_PASSWORD -P anmn_ts -s anmn_ts"
 
Note that the same thing happens from the context of the WPS process, which can be triggered equivalently from the portal.

**What happens**
After a minute or two:

<blockquote>
Write exception
java.lang.IllegalArgumentException: dimension length must be > 0 :0
	at ucar.nc2.NetcdfFileWriteable.addDimension(NetcdfFileWriteable.java:247)
	at au.org.emii.ncdfgenerator.DimensionImpl.define(DimensionImpl.java:26)
	at au.org.emii.ncdfgenerator.NcdfEncoder.writeNext(NcdfEncoder.java:188)
	at au.org.emii.ncdfgenerator.Main.main(Main.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
</blockquote>

**What should happen**
A valid zip of NetCDF files is produced.

**Comment by danfruehauf** [comment]
You left the password here in plain text. Just removed it.

**Comment by jkburges** [comment]
Oops :-(
